---
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
branches:
  only:
    - master
skip_tags: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
before_build:
  - nuget update -self
  - nuget restore
test_script:
  - dotnet test .\PrismaDB-QueryParser-Test\PrismaDB-QueryParser-Test.csproj --no-build
configuration: Release
image: "Visual Studio 2017"
nuget:
  disable_publish_on_pr: true
cache:
  - '%USERPROFILE%\.nuget\packages'
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
version: "0.1.{build}"
init:
  - ps: |
        if (($env:APPVEYOR_REPO_COMMIT_MESSAGE -match '^v\d+\.\d+$') -And `
            ($env:APPVEYOR_REPO_BRANCH -eq 'master') -And `
            ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) ) # new version release
        {
          Invoke-RestMethod -Uri 'https://ci.appveyor.com/project/bazzilic/prismadb-queryparser/settings/build-number' `
                            -Headers @{ "Authorization" = "Bearer ${env:AppVeyorAPIToken}" ; "Content-type" = "application/json" } `
                            -Method Put `
                            -Body '{ nextBuildNumber: 1 }'
          $env:APPVEYOR_REPO_TAG_NAME -match '^v(\d+)\.(\d+)$'
          [int]$major = $Matches[1]/1
          [int]$minor = $Matches[2]/1
          Update-AppVeyorBuild -Version "$major.$minor.0"
        }
